module.exports={
   MONGOURL:"mongodb+srv://anjali:123@cluster0.rv6v1.mongodb.net/BlogApp?retryWrites=true&w=majority"
}
//if(process.env.MODE==='production')
//{
//module.exports=require('./prod');
//}else
//{
//module.exports=require('./devs');
//}